<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8752" started-at="2016-12-01T09:27:19Z" finished-at="2016-12-01T09:27:28Z">
    <groups>
    </groups>
    <test name="login test" duration-ms="8752" started-at="2016-12-01T09:27:19Z" finished-at="2016-12-01T09:27:28Z">
      <class name="com.wangsy.doTest.LoginTest">
        <test-method status="PASS" signature="beforeLogin()[pri:0, instance:com.wangsy.doTest.LoginTest@d2cc05a]" name="beforeLogin" is-config="true" duration-ms="6756" started-at="2016-12-01T17:27:19Z" finished-at="2016-12-01T17:27:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeLogin -->
        <test-method status="SKIP" signature="testLogin(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.wangsy.doTest.LoginTest@d2cc05a]" name="testLogin" duration-ms="0" started-at="2016-12-01T17:27:26Z" data-provider="userLogin" finished-at="2016-12-01T17:27:26Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.wangsy.Utils.ExcelUtils.getDataForTestNG(ExcelUtils.java:75)
	at com.wangsy.doTest.LoginTest.rangeData(LoginTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.wangsy.doTest.LoginTest@d2cc05a]" name="quit" is-config="true" duration-ms="1759" started-at="2016-12-01T17:27:26Z" finished-at="2016-12-01T17:27:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.wangsy.doTest.LoginTest -->
    </test> <!-- login test -->
  </suite> <!-- Default suite -->
</testng-results>
